[package]
name = "music_player"
version = "0.1.0"
edition = "2021"

[dependencies]        
rodio = "0.17"        
soloud = "1.0.5"
fltk-sys = { version = "1.4"}
fltk = "1.4" 
lazy_static = "1.4"
thiserror = "1.0"



